apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-resource-limits.yaml
  - deny-public-loadbalancer.yaml
  - restrict-model-namespace.yaml
  - require-sa-token-control.yaml
  - deny-default-sa-use.yaml
