apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyPublicLoadBalancer
metadata:
  name: deny-public-loadbalancer
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    allowedNamespaces:
      - kong
