apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNoUseDefaultServiceAccount
metadata:
  name: no-default-serviceaccount
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job", "CronJob"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - flux-system
      - monitoring