apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictModelNamespace
metadata:
  name: restrict-model-namespace
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedNamespace: ai-workloads
